### ISSUE TITLE
No code yet

### ISSUE THREAD

**Issue by pranavkarthik10** [SWC-Python-Club/rock-paper-scissors-practice#1]
Where is the code?

**Comment by vincent-qc** [comment]
Joe is working on the funne code

**Comment by JerryXiong69** [comment]
Nice 
Funne code? Mario?

**Comment by JerryXiong69** [comment]
OH I SEE. Feel free to throw it in main!

**Comment by jo3-l** [comment]
Just fyi @JerryXiong69 we don't have write access so you'll need to merge 👀

**Comment by JerryXiong69** [comment]
Right yes...
